[
	{
		"players": [
			{"Team":"Arsenal","Number":"1","Name":"Wojciech Szczęsny","Nat":"POL","Pos":"G","Height":"1.95","Weight":"84","DOB":"18-04-90","Birth Place":"Warsaw","PreviousClub":"Legia Warszawa"},
			{"Team":"Arsenal","Number":"2","Name":"Mathieu Debuchy","Nat":"FRA","Pos":"D","Height":"1.77","Weight":"74","DOB":"28-07-85","Birth Place":"Fretin","PreviousClub":"Newcastle U"},
			{"Team":"Arsenal","Number":"3","Name":"Kieran Gibbs","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"70","DOB":"26-09-89","Birth Place":"Lambeth","PreviousClub":"None"},
			{"Team":"Arsenal","Number":"4","Name":"Per Mertesacker","Nat":"GER","Pos":"D","Height":"1.98","Weight":"90","DOB":"29-09-84","Birth Place":"Hannover","PreviousClub":"Werder Bremen"},
			{"Team":"Arsenal","Number":"6","Name":"Laurent Koscielny","Nat":"FRA","Pos":"D","Height":"1.86","Weight":"75","DOB":"10-09-85","Birth Place":"Tulle","PreviousClub":"Lorient"},
			{"Team":"Arsenal","Number":"7","Name":"Tomáš Rosický","Nat":"CZE","Pos":"M","Height":"1.78","Weight":"67","DOB":"04-10-80","Birth Place":"Prague","PreviousClub":"Borussia Dortmund"},
			{"Team":"Arsenal","Number":"8","Name":"Mikel Arteta","Nat":"ESP","Pos":"M","Height":"1.75","Weight":"69","DOB":"26-03-82","Birth Place":"San Sebastián","PreviousClub":"Everton"},
			{"Team":"Arsenal","Number":"9","Name":"Lukas Podolski","Nat":"GER","Pos":"F","Height":"1.82","Weight":"83","DOB":"04-06-85","Birth Place":"Gliwice","PreviousClub":"Köln"},
			{"Team":"Arsenal","Number":"10","Name":"Jack Wilshere","Nat":"ENG","Pos":"M","Height":"1.70","Weight":"65","DOB":"01-01-92","Birth Place":"Stevenage","PreviousClub":"None"},
			{"Team":"Arsenal","Number":"11","Name":"Mesut Özil","Nat":"GER","Pos":"M","Height":"1.82","Weight":"73","DOB":"15-10-88","Birth Place":"Gelsenkirchen","PreviousClub":"Real Madrid"},
			{"Team":"Arsenal","Number":"12","Name":"Olivier Giroud","Nat":"FRA","Pos":"F","Height":"1.92","Weight":"88","DOB":"30-09-86","Birth Place":"Chambéry","PreviousClub":"Montpellier"},
			{"Team":"Arsenal","Number":"13","Name":"David Ospina","Nat":"COL","Pos":"G","Height":"1.81","Weight":"76","DOB":"31-08-88","Birth Place":"Medellín","PreviousClub":"Nice"},
			{"Team":"Arsenal","Number":"14","Name":"Theo Walcott","Nat":"ENG","Pos":"F","Height":"1.75","Weight":"68","DOB":"16-03-89","Birth Place":"Stanmore","PreviousClub":"Southampton"},
			{"Team":"Arsenal","Number":"15","Name":"Alex Oxlade-Chamberlain","Nat":"ENG","Pos":"M","Height":"1.80","Weight":"70","DOB":"15-08-93","Birth Place":"Portsmouth","PreviousClub":"Southampton"},
			{"Team":"Arsenal","Number":"16","Name":"Aaron Ramsey","Nat":"WAL","Pos":"M","Height":"1.78","Weight":"76","DOB":"26-12-90","Birth Place":"Caerphilly","PreviousClub":"Cardiff C"},
			{"Team":"Arsenal","Number":"17","Name":"Alexis Sánchez","Nat":"CHI","Pos":"F","Height":"1.68","Weight":"62","DOB":"19-12-88","Birth Place":"Tocopilla","PreviousClub":"Barcelona"},
			{"Team":"Arsenal","Number":"18","Name":"Nacho Monreal","Nat":"ESP","Pos":"D","Height":"1.78","Weight":"72","DOB":"26-02-86","Birth Place":"Pamplona","PreviousClub":"Málaga"},
			{"Team":"Arsenal","Number":"19","Name":"Santi Cazorla","Nat":"ESP","Pos":"M","Height":"1.68","Weight":"66","DOB":"13-12-84","Birth Place":"Lugo de Llanera","PreviousClub":"Málaga"},
			{"Team":"Arsenal","Number":"20","Name":"Mathieu Flamini","Nat":"FRA","Pos":"M","Height":"1.78","Weight":"67","DOB":"07-03-84","Birth Place":"Marseille","PreviousClub":"Milan"},
			{"Team":"Arsenal","Number":"21","Name":"Calum Chambers","Nat":"ENG","Pos":"D","Height":"1.82","Weight":"66","DOB":"20-01-95","Birth Place":"Petersfield","PreviousClub":"Southampton"},
			{"Team":"Arsenal","Number":"22","Name":"Yaya Sanogo","Nat":"FRA","Pos":"F","Height":"1.91","Weight":"74","DOB":"27-01-93","Birth Place":"Massy","PreviousClub":"Auxerre"},
			{"Team":"Arsenal","Number":"24","Name":"Abou Diaby","Nat":"FRA","Pos":"M","Height":"1.88","Weight":"75","DOB":"11-05-86","Birth Place":"Paris","PreviousClub":"Auxerre"},
			{"Team":"Arsenal","Number":"27","Name":"Serge Gnabry","Nat":"GER","Pos":"M","Height":"1.73","Weight":"73","DOB":"14-07-95","Birth Place":"Stuttgart","PreviousClub":"Stuttgart"},
			{"Team":"Arsenal","Number":"28","Name":"Joel Campbell","Nat":"CRC","Pos":"F","Height":"1.78","Weight":"70","DOB":"26-06-92","Birth Place":"San José [CRC]","PreviousClub":"Deportivo Saprissa"},
			{"Team":"Aston Villa","Number":"1","Name":"Brad Guzan","Nat":"USA","Pos":"G","Height":"1.93","Weight":"94","DOB":"09-09-84","Birth Place":"Home Glen","PreviousClub":"Chivas USA"},
			{"Team":"Aston Villa","Number":"2","Name":"Nathan Baker","Nat":"ENG","Pos":"D","Height":"1.91","Weight":"80","DOB":"23-04-91","Birth Place":"Worcester","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"3","Name":"Joe Bennett","Nat":"ENG","Pos":"D","Height":"1.77","Weight":"74","DOB":"28-03-90","Birth Place":"Rochdale","PreviousClub":"Middlesbrough"},
			{"Team":"Aston Villa","Number":"4","Name":"Ron Vlaar","Nat":"NED","Pos":"D","Height":"1.89","Weight":"80","DOB":"16-02-85","Birth Place":"Hensbroek","PreviousClub":"Feyenoord"},
			{"Team":"Aston Villa","Number":"5","Name":"Jores Okore","Nat":"DEN","Pos":"D","Height":"1.83","Weight":"80","DOB":"11-08-92","Birth Place":"Abidjan","PreviousClub":"FC Nordsjælland"},
			{"Team":"Aston Villa","Number":"6","Name":"Ciaran Clark","Nat":"IRL","Pos":"D","Height":"1.88","Weight":"76","DOB":"26-09-89","Birth Place":"Harrow","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"7","Name":"Leandro Bacuna","Nat":"NED","Pos":"M","Height":"1.87","Weight":"77","DOB":"21-08-91","Birth Place":"Groningen","PreviousClub":"FC Groningen"},
			{"Team":"Aston Villa","Number":"8","Name":"Karim El Ahmadi","Nat":"MAR","Pos":"M","Height":"1.85","Weight":"78","DOB":"27-01-85","Birth Place":"Enschede","PreviousClub":"Feyenoord"},
			{"Team":"Aston Villa","Number":"10","Name":"Andreas Weimann","Nat":"AUT","Pos":"F","Height":"1.88","Weight":"76","DOB":"05-08-91","Birth Place":"Vienna","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"11","Name":"Gabriel Agbonlahor","Nat":"ENG","Pos":"F","Height":"1.80","Weight":"79","DOB":"13-10-86","Birth Place":"Birmingham","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"12","Name":"Joe Cole","Nat":"ENG","Pos":"M","Height":"1.76","Weight":"73","DOB":"08-11-81","Birth Place":"Paddington","PreviousClub":"West Ham U"},
			{"Team":"Aston Villa","Number":"14","Name":"Philippe Senderos","Nat":"SUI","Pos":"D","Height":"1.90","Weight":"84","DOB":"14-02-85","Birth Place":"Geneva","PreviousClub":"Valencia"},
			{"Team":"Aston Villa","Number":"15","Name":"Ashley Westwood","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"67","DOB":"01-04-90","Birth Place":"Nantwich","PreviousClub":"Crewe Alex"},
			{"Team":"Aston Villa","Number":"16","Name":"Fabian Delph","Nat":"ENG","Pos":"M","Height":"1.74","Weight":"60","DOB":"21-11-89","Birth Place":"Bradford","PreviousClub":"Leeds U"},
			{"Team":"Aston Villa","Number":"17","Name":"Chris Herd","Nat":"AUS","Pos":"M","Height":"1.73","Weight":"76","DOB":"04-04-89","Birth Place":"Perth [AUS]","PreviousClub":"Bayswater C"},
			{"Team":"Aston Villa","Number":"18","Name":"Kieran Richardson","Nat":"ENG","Pos":"M","Height":"1.79","Weight":"74","DOB":"21-10-84","Birth Place":"Greenwich","PreviousClub":"Fulham"},
			{"Team":"Aston Villa","Number":"19","Name":"Darren Bent","Nat":"ENG","Pos":"F","Height":"1.80","Weight":"73","DOB":"06-02-84","Birth Place":"Tooting","PreviousClub":"Sunderland"},
			{"Team":"Aston Villa","Number":"20","Name":"Christian Benteke","Nat":"BEL","Pos":"F","Height":"1.90","Weight":"83","DOB":"03-12-90","Birth Place":"Kinshasa","PreviousClub":"KRC Genk"},
			{"Team":"Aston Villa","Number":"21","Name":"Alan Hutton","Nat":"SCO","Pos":"D","Height":"1.85","Weight":"72","DOB":"30-11-84","Birth Place":"Glasgow","PreviousClub":"Tottenham H"},
			{"Team":"Aston Villa","Number":"22","Name":"Gary Gardner","Nat":"ENG","Pos":"M","Height":"1.88","Weight":"82","DOB":"29-06-92","Birth Place":"Solihull","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"23","Name":"Aly Cissokho","Nat":"FRA","Pos":"D","Height":"1.81","Weight":"75","DOB":"15-09-87","Birth Place":"Blois","PreviousClub":"Valencia"},
			{"Team":"Aston Villa","Number":"27","Name":"Libor Kozák","Nat":"CZE","Pos":"F","Height":"1.93","Weight":"82","DOB":"30-05-89","Birth Place":"Brumov-Bylnice","PreviousClub":"Lazio"},
			{"Team":"Aston Villa","Number":"28","Name":"Charles N'Zogbia","Nat":"FRA","Pos":"M","Height":"1.70","Weight":"70","DOB":"28-05-86","Birth Place":"Harfleur","PreviousClub":"Wigan Ath"},
			{"Team":"Aston Villa","Number":"31","Name":"Shay Given","Nat":"IRL","Pos":"G","Height":"1.88","Weight":"84","DOB":"20-04-76","Birth Place":"Lifford","PreviousClub":"Manchester C"},
			{"Team":"Aston Villa","Number":"34","Name":"Matthew Lowton","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"78","DOB":"09-06-89","Birth Place":"Chesterfield","PreviousClub":"Sheffield U"},
			{"Team":"Aston Villa","Number":"35","Name":"Enda Stevens","Nat":"IRL","Pos":"D","Height":"1.83","Weight":"78","DOB":"09-07-90","Birth Place":"Dublin","PreviousClub":"Shamrock R"},
			{"Team":"Aston Villa","Number":"37","Name":"Callum Robinson","Nat":"ENG","Pos":"F","Height":"1.78","Weight":"75","DOB":"02-02-95","Birth Place":"Northampton","PreviousClub":"None"},
			{"Team":"Aston Villa","Number":"38","Name":"Graham Burke","Nat":"IRL","Pos":"F","Height":"1.80","Weight":"75","DOB":"21-09-93","Birth Place":"Dublin","PreviousClub":"Belvedere"},
			{"Team":"Aston Villa","Number":"40","Name":"Jack Grealish","Nat":"IRL","Pos":"M","Height":"1.75","Weight":"68","DOB":"10-09-95","Birth Place":"Birmingham","PreviousClub":"None"},
			{"Team": "Burnley", "Number":"1","Name":"Thomas Heaton","Nat":"ENG","Pos":"G","Height":"1.85","Weight":"85","DOB":"15-04-86","Birth Place":"Chester","PreviousClub":"Bristol C"},
			{"Team": "Burnley", "Number":"2","Name":"Kieran Trippier","Nat":"ENG","Pos":"D","Height":"1.78","Weight":"71","DOB":"19-09-90","Birth Place":"Bury","PreviousClub":"Manchester C"},
			{"Team": "Burnley", "Number":"3","Name":"Danny Lafferty","Nat":"NIR","Pos":"D","Height":"1.82","Weight":"80","DOB":"01-04-89","Birth Place":"Derry","PreviousClub":"Derry C"},
			{"Team": "Burnley", "Number":"4","Name":"Michael Duff","Nat":"NIR","Pos":"D","Height":"1.85","Weight":"74","DOB":"11-01-78","Birth Place":"Belfast","PreviousClub":"Cheltenham\n T"},
			{"Team": "Burnley", "Number":"5","Name":"Jason Shackell","Nat":"ENG","Pos":"D","Height":"1.93","Weight":"83","DOB":"27-09-83","Birth Place":"Stevenage","PreviousClub":"Derby Co"},
			{"Team": "Burnley", "Number":"6","Name":"Ben Mee","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"74","DOB":"23-09-89","Birth Place":"Sale","PreviousClub":"Manchester C"},
			{"Team": "Burnley", "Number":"7","Name":"Ross Wallace","Nat":"SCO","Pos":"M","Height":"1.68","Weight":"64","DOB":"23-05-85","Birth Place":"Dundee","PreviousClub":"Preston NE"},
			{"Team": "Burnley", "Number":"8","Name":"Dean Marney","Nat":"ENG","Pos":"M","Height":"1.83","Weight":"72","DOB":"31-01-84","Birth Place":"Barking","PreviousClub":"Hull C"},
			{"Team": "Burnley", "Number":"9","Name":"Sam Vokes","Nat":"WAL","Pos":"F","Height":"1.86","Weight":"76","DOB":"21-10-89","Birth Place":"Lymington","PreviousClub":"Wolverhampton W"},
			{"Team": "Burnley", "Number":"10","Name":"Danny Ings","Nat":"ENG","Pos":"F","Height":"1.78","Weight":"73","DOB":"16-03-92","Birth Place":"Winchester","PreviousClub":"Bournemouth"},
			{"Team": "Burnley", "Number":"11","Name":"Michael Kightly","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"64","DOB":"24-01-86","Birth Place":"Basildon","PreviousClub":"Stoke C"},
			{"Team": "Burnley", "Number":"12","Name":"Alex Cisak","Nat":"AUS","Pos":"G","Height":"1.90","Weight":"94","DOB":"19-05-89","Birth Place":"Kraków","PreviousClub":"Oldham Ath"},
			{"Team": "Burnley", "Number":"14","Name":"David Jones","Nat":"ENG","Pos":"M","Height":"1.85","Weight":"80","DOB":"04-11-84","Birth Place":"Southport","PreviousClub":"Wigan Ath"},
			{"Team": "Burnley", "Number":"15","Name":"Matthew Taylor","Nat":"ENG","Pos":"M","Height":"1.78","Weight":"74","DOB":"27-11-81","Birth Place":"Oxford","PreviousClub":"West Ham U"},
			{"Team": "Burnley", "Number":"17","Name":"Marvin Sordell","Nat":"ENG","Pos":"F","Height":"1.77","Weight":"79","DOB":"17-02-91","Birth Place":"Brent","PreviousClub":"Bolton W"},
			{"Team": "Burnley", "Number":"18","Name":"Steven Reid","Nat":"IRL","Pos":"D","Height":"1.85","Weight":"87","DOB":"10-03-81","Birth Place":"Kingston","PreviousClub":"WBA"},
			{"Team": "Burnley", "Number":"19","Name":"Lukas Jutkiewicz","Nat":"ENG","Pos":"F","Height":"1.85","Weight":"73","DOB":"28-03-89","Birth Place":"Southampton","PreviousClub":"Middlesbrough"},
			{"Team": "Burnley", "Number":"22","Name":"Matthew Gilks","Nat":"SCO","Pos":"G","Height":"1.85","Weight":"81","DOB":"04-06-82","Birth Place":"Rochdale","PreviousClub":"Blackpool"},
			{"Team": "Burnley", "Number":"28","Name":"Kevin Long","Nat":"IRL","Pos":"D","Height":"1.88","Weight":"83","DOB":"18-08-90","Birth Place":"Cork","PreviousClub":"Cork C"},
			{"Team": "Burnley", "Number":"30","Name":"Ashley Barnes","Nat":"AUT","Pos":"F","Height":"1.83","Weight":"71","DOB":"31-10-89","Birth Place":"Bath","PreviousClub":"Brighton & HA"},
			{"Team": "Burnley", "Number":"33","Name":"Steven Hewitt","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"67","DOB":"05-12-93","Birth Place":"Manchester","PreviousClub":"None"},
			{"Team": "Burnley", "Number":"34","Name":"Tom Anderson","Nat":"ENG","Pos":"D","Height":"1.93","Weight":"83","DOB":"02-09-93","Birth Place":"Burnley","PreviousClub":"None"},
			{"Team": "Burnley", "Number":"37","Name":"Scott Arfield","Nat":"SCO","Pos":"M","Height":"1.78","Weight":"64","DOB":"01-11-88","Birth Place":"Dechmont","PreviousClub":"Huddersfield T"},
			{"Team": "Burnley", "Number":"38","Name":"Cameron Dummigan","Nat":"NIR","Pos":"D","Height":"1.80","Weight":"70","DOB":"02-06-96","Birth Place":"Lurgan","PreviousClub":"Cliftonville"},
			{"Team": "Burnley", "Number":"44","Name":"Jason Gilchrist","Nat":"ENG","Pos":"F","Height":"1.78","Weight":"66","DOB":"17-12-94","Birth Place":"St Helens","PreviousClub":"Manchester C"},
			{"Team": "Chelsea", "Number":"1","Name":"Petr Čech","Nat":"CZE","Pos":"G","Height":"1.96","Weight":"90","DOB":"20-05-82","Birth Place":"Plzeň","PreviousClub":"Rennes"},
			{"Team": "Chelsea", "Number":"2","Name":"Branislav Ivanović","Nat":"SRB","Pos":"D","Height":"1.88","Weight":"86","DOB":"22-02-84","Birth Place":"Sremska Mitrovica","PreviousClub":"Lokomotiv Moscow"},
			{"Team": "Chelsea", "Number":"3","Name":"Filipe Luis","Nat":"BRA","Pos":"D","Height":"1.82","Weight":"70","DOB":"09-08-85","Birth Place":"Jaraguá do Sul","PreviousClub":"Atlético Madrid"},
			{"Team": "Chelsea", "Number":"4","Name":"Cesc Fàbregas","Nat":"ESP","Pos":"M","Height":"1.77","Weight":"69","DOB":"04-05-87","Birth Place":"Arenys de Mar","PreviousClub":"Barcelona"},
			{"Team": "Chelsea", "Number":"5","Name":"Kurt Zouma","Nat":"FRA","Pos":"D","Height":"1.87","Weight":"85","DOB":"27-10-94","Birth Place":"Lyon","PreviousClub":"St-Etienne"},
			{"Team": "Chelsea", "Number":"7","Name":"Ramires","Nat":"BRA","Pos":"M","Height":"1.79","Weight":"65","DOB":"24-03-87","Birth Place":"Rio de Janeiro","PreviousClub":"Benfica"},
			{"Team": "Chelsea", "Number":"9","Name":"Fernando Torres","Nat":"ESP","Pos":"F","Height":"1.86","Weight":"78","DOB":"20-03-84","Birth Place":"Madrid","PreviousClub":"Liverpool"},
			{"Team": "Chelsea", "Number":"10","Name":"Eden Hazard","Nat":"BEL","Pos":"M","Height":"1.70","Weight":"69","DOB":"07-01-91","Birth Place":"La Louvière","PreviousClub":"Lille"},
			{"Team": "Chelsea", "Number":"11","Name":"Oscar","Nat":"BRA","Pos":"M","Height":"1.79","Weight":"66","DOB":"09-09-91","Birth Place":"Americana","PreviousClub":"Internacional"},
			{"Team": "Chelsea", "Number":"12","Name":"Mikel John Obi","Nat":"NGA","Pos":"M","Height":"1.84","Weight":"85","DOB":"22-04-87","Birth Place":"Jos","PreviousClub":"Lyn"},
			{"Team": "Chelsea", "Number":"14","Name":"Andre Schürrle","Nat":"GER","Pos":"M","Height":"1.75","Weight":"63","DOB":"06-11-90","Birth Place":"Ludwigshafen","PreviousClub":"Bayer Leverkusen"},
			{"Team": "Chelsea", "Number":"15","Name":"Didier Drogba","Nat":"CIV","Pos":"F","Height":"1.89","Weight":"91","DOB":"11-03-78","Birth Place":"Abidjan","PreviousClub":"Galatasaray"},
			{"Team": "Chelsea", "Number":"16","Name":"Marco van Ginkel","Nat":"NED","Pos":"M","Height":"1.80","Weight":"67","DOB":"01-12-92","Birth Place":"Amersfoort","PreviousClub":"Vitesse"},
			{"Team": "Chelsea", "Number":"17","Name":"Mohamed Salah","Nat":"EGY","Pos":"M","Height":"1.75","Weight":"69","DOB":"15-06-92","Birth Place":"Basyoun","PreviousClub":"Basel"},
			{"Team": "Chelsea", "Number":"19","Name":"Diego Costa","Nat":"ESP","Pos":"F","Height":"1.86","Weight":"78","DOB":"07-10-88","Birth Place":"Lagarto","PreviousClub":"Atlético Madrid"},
			{"Team": "Chelsea", "Number":"21","Name":"Nemanja Matić","Nat":"SRB","Pos":"M","Height":"1.94","Weight":"82","DOB":"01-08-88","Birth Place":"Šabac","PreviousClub":"Benfica"},
			{"Team": "Chelsea", "Number":"22","Name":"Willian","Nat":"BRA","Pos":"M","Height":"1.74","Weight":"70","DOB":"09-08-88","Birth Place":"Ribeirão Pires","PreviousClub":"Anzhi Makhachkala"},
			{"Team": "Chelsea", "Number":"23","Name":"Mark Schwarzer","Nat":"AUS","Pos":"G","Height":"1.94","Weight":"85","DOB":"06-10-72","Birth Place":"Sydney","PreviousClub":"Fulham"},
			{"Team": "Chelsea", "Number":"24","Name":"Gary Cahill","Nat":"ENG","Pos":"D","Height":"1.88","Weight":"71","DOB":"19-12-85","Birth Place":"Sheffield","PreviousClub":"Bolton W"},
			{"Team": "Chelsea", "Number":"26","Name":"John Terry","Nat":"ENG","Pos":"D","Height":"1.86","Weight":"91","DOB":"07-12-80","Birth Place":"Barking","PreviousClub":"None"},
			{"Team": "Chelsea", "Number":"27","Name":"Nathan Aké","Nat":"NED","Pos":"D","Height":"1.80","Weight":"71","DOB":"18-02-95","Birth Place":"Den Haag","PreviousClub":"Feyenoord"},
			{"Team": "Chelsea", "Number":"28","Name":"César Azpilicueta","Nat":"ESP","Pos":"D","Height":"1.78","Weight":"70","DOB":"28-08-89","Birth Place":"Pamplona","PreviousClub":"Marseille"},
			{"Team": "Chelsea", "Number":"46","Name":"Jamal Blackman","Nat":"ENG","Pos":"G","Height":"1.96","Weight":"82","DOB":"27-10-93","Birth Place":"Croydon","PreviousClub":"None"},
			{"Team": "Everton", "Number":"1","Name":"Joel Robles","Nat":"ESP","Pos":"G","Height":"1.95","Weight":"85","DOB":"17-06-90","Birth Place":"Leganés","Previous Club":"Atlético Madrid"},
			{"Team": "Everton", "Number":"2","Name":"Tony Hibbert","Nat":"ENG","Pos":"D","Height":"1.73","Weight":"72","DOB":"20-02-81","Birth Place":"Liverpool","PreviousClub":"None"},
			{"Team": "Everton", "Number":"3","Name":"Leighton Baines","Nat":"ENG","Pos":"D","Height":"1.70","Weight":"75","DOB":"11-12-84","Birth Place":"Liverpool","PreviousClub":"Wigan Ath"},
			{"Team": "Everton", "Number":"4","Name":"Darron Gibson","Nat":"IRL","Pos":"M","Height":"1.80","Weight":"83","DOB":"25-10-87","Birth Place":"Derry","PreviousClub":"Manchester U"},
			{"Team": "Everton", "Number":"6","Name":"Phil Jagielka","Nat":"ENG","Pos":"D","Height":"1.83","Weight":"83","DOB":"17-08-82","Birth Place":"Sale","PreviousClub":"Sheffield U"},
			{"Team": "Everton", "Number":"7","Name":"Aidan McGeady","Nat":"IRL","Pos":"M","Height":"1.78","Weight":"72","DOB":"04-04-86","Birth Place":"Glasgow","PreviousClub":"Spartak Moscow"},
			{"Team": "Everton", "Number":"8","Name":"Bryan Oviedo","Nat":"CRC","Pos":"M","Height":"1.72","Weight":"70","DOB":"18-02-90","Birth Place":"Alajuela","PreviousClub":"FC København"},
			{"Team": "Everton", "Number":"9","Name":"Arouna Koné","Nat":"CIV","Pos":"F","Height":"1.81","Weight":"81","DOB":"11-11-83","Birth Place":"Anyama","PreviousClub":"Wigan Ath"},
			{"Team": "Everton", "Number":"10","Name":"Romelu Lukaku","Nat":"BEL","Pos":"F","Height":"1.90","Weight":"94","DOB":"13-05-93","Birth Place":"Antwerp","PreviousClub":"Chelsea"},
			{"Team": "Everton", "Number":"11","Name":"Kevin Mirallas","Nat":"BEL","Pos":"F","Height":"1.78","Weight":"72","DOB":"05-10-87","Birth Place":"Liège","PreviousClub":"Olympiakos"},
			{"Team": "Everton", "Number":"14","Name":"Steven Naismith","Nat":"SCO","Pos":"F","Height":"1.78","Weight":"72","DOB":"14-09-86","Birth Place":"Irvine","PreviousClub":"Rangers"},
			{"Team": "Everton", "Number":"15","Name":"Sylvain Distin","Nat":"FRA","Pos":"D","Height":"1.93","Weight":"85","DOB":"16-12-77","Birth Place":"Bagnolet","PreviousClub":"Portsmouth"},
			{"Team": "Everton", "Number":"16","Name":"James McCarthy","Nat":"IRL","Pos":"M","Height":"1.80","Weight":"72","DOB":"12-11-90","Birth Place":"Glasgow","PreviousClub":"Wigan Ath"},
			{"Team": "Everton", "Number":"17","Name":"Muhamed Bešić","Nat":"BIH","Pos":"M","Height":"1.77","Weight":"75","DOB":"10-09-92","Birth Place":"Berlin","PreviousClub":"Ferencváros"},
			{"Team": "Everton", "Number":"18","Name":"Gareth Barry","Nat":"ENG","Pos":"M","Height":"1.83","Weight":"79","DOB":"23-02-81","Birth Place":"Hastings","PreviousClub":"Manchester C"},
			{"Team": "Everton", "Number":"19","Name": "Christian Atsu","Nat": "GHA","Pos":"M"},
			{"Team": "Everton", "Number":"20","Name":"Ross Barkley","Nat":"ENG","Pos":"M","Height":"1.89","Weight":"76","DOB":"05-12-93","Birth Place":"Liverpool","PreviousClub":"None"},
			{"Team": "Everton", "Number":"21","Name":"Leon Osman","Nat":"ENG","Pos":"M","Height":"1.73","Weight":"62","DOB":"17-05-81","Birth Place":"Billinge","PreviousClub":"None"},
			{"Team": "Everton", "Number":"22","Name":"Steven Pienaar","Nat":"RSA","Pos":"M","Height":"1.70","Weight":"66","DOB":"17-03-82","Birth Place":"Johannesburg","PreviousClub":"Tottenham H"},
			{"Team": "Everton", "Number":"23","Name":"Séamus Coleman","Nat":"IRL","Pos":"D","Height":"1.93","Weight":"67","DOB":"11-10-88","Birth Place":"Donegal","PreviousClub":"Sligo R"},
			{"Team": "Everton", "Number":"24","Name":"Tim Howard","Nat":"USA","Pos":"G","Height":"1.91","Weight":"95","DOB":"06-03-79","Birth Place":"North Brunswick","PreviousClub":"Manchester\n U"},
			{"Team": "Everton", "Number":"26","Name":"John Stones","Nat":"ENG","Pos":"D","Height":"1.88","Weight":"70","DOB":"28-05-94","Birth Place":"Barnsley","PreviousClub":"Barnsley"},
			{"Team": "Everton", "Number":"32","Name":"Antolín Alcaraz","Nat":"PAR","Pos":"D","Height":"1.84","Weight":"80","DOB":"30-07-82","Birth Place":"Roque Gonzalez","PreviousClub":"Wigan Ath"},
			{"Team":"Liverpool", "Number":"1","Name":"Brad Jones","Nat":"AUS","Pos":"G","Height":"1.91","Weight":"76","DOB":"19-03-82","Birth Place":"Armadale","PreviousClub":"Middlesbrough"},
			{"Team":"Liverpool", "Number":"2","Name":"Glen Johnson","Nat":"ENG","Pos":"D","Height":"1.82","Weight":"70","DOB":"23-08-84","Birth Place":"Greenwich","PreviousClub":"Portsmouth"},
			{"Team":"Liverpool", "Number":"3","Name":"José Enrique","Nat":"ESP","Pos":"D","Height":"1.84","Weight":"82","DOB":"23-01-86","Birth Place":"Valencia","PreviousClub":"Newcastle U"},
			{"Team":"Liverpool", "Number":"4","Name":"Kolo Touré","Nat":"CIV","Pos":"D","Height":"1.83","Weight":"76","DOB":"19-03-81","Birth Place":"Sokoura Bouaké","PreviousClub":"Manchester C"},
			{"Team":"Liverpool", "Number":"5","Name":"Daniel Agger","Nat":"DEN","Pos":"D","Height":"1.87","Weight":"75","DOB":"12-12-84","Birth Place":"Hvidovre","PreviousClub":"Brøndby"},
			{"Team":"Liverpool", "Number":"6","Name":"Dejan Lovren","Nat":"CRO","Pos":"D","Height":"1.88","Weight":"86","DOB":"05-07-89","Birth Place":"Karlovac","PreviousClub":"Southampton"},
			{"Team":"Liverpool", "Number":"8","Name":"Steven Gerrard","Nat":"ENG","Pos":"M","Height":"1.83","Weight":"79","DOB":"30-05-80","Birth Place":"Whiston","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"9","Name":"Rickie Lambert","Nat":"ENG","Pos":"F","Height":"1.88","Weight":"77","DOB":"16-02-82","Birth Place":"Liverpool","PreviousClub":"Southampton"},
			{"Team":"Liverpool", "Number":"10","Name":"Philippe Coutinho","Nat":"BRA","Pos":"M","Height":"1.71","Weight":"68","DOB":"12-06-92","Birth Place":"Rio de Janeiro","PreviousClub":"Internazionale"},
			{"Team":"Liverpool", "Number":"11","Name":"Oussama Assaidi","Nat":"MAR","Pos":"M","Height":"1.78","Weight":"70","DOB":"05-08-88","Birth Place":"Beni Boughafar","PreviousClub":"SC Heerenveen"},
			{"Team":"Liverpool", "Number":"14","Name":"Jordan Henderson","Nat":"ENG","Pos":"M","Height":"1.82","Weight":"67","DOB":"17-06-90","Birth Place":"Sunderland","PreviousClub":"Sunderland"},
			{"Team":"Liverpool", "Number":"15","Name":"Daniel Sturridge","Nat":"ENG","Pos":"F","Height":"1.88","Weight":"76","DOB":"01-09-89","Birth Place":"Birmingham","PreviousClub":"Chelsea"},
			{"Team":"Liverpool", "Number":"16","Name":"Sebastián Coates","Nat":"URU","Pos":"D","Height":"1.96","Weight":"88","DOB":"07-10-90","Birth Place":"Montevideo","PreviousClub":"Nacional [URU]"},
			{"Team":"Liverpool", "Number":"17","Name":"Mamadou Sakho","Nat":"FRA","Pos":"D","Height":"1.87","Weight":"83","DOB":"13-02-90","Birth Place":"Paris","PreviousClub":"Paris St-Germain"},
			{"Team":"Liverpool", "Number":"19","Name":"Javi Manquillo","Nat":"ESP","Pos":"D","Height":"1.72","Weight":"62","DOB":"05-05-94","Birth Place":"Madrid","PreviousClub":"Atlético Madrid"},
			{"Team":"Liverpool", "Number":"20","Name":"Adam Lallana","Nat":"ENG","Pos":"M","Height":"1.73","Weight":"73","DOB":"10-05-88","Birth Place":"St Albans","PreviousClub":"Southampton"},
			{"Team":"Liverpool", "Number":"21","Name":"Lucas Leiva","Nat":"BRA","Pos":"M","Height":"1.79","Weight":"74","DOB":"09-01-87","Birth Place":"Dourados","PreviousClub":"Grêmio"},
			{"Team":"Liverpool", "Number":"22","Name":"Simon Mignolet","Nat":"BEL","Pos":"G","Height":"1.93","Weight":"87","DOB":"06-03-88","Birth Place":"Sint-Truiden","PreviousClub":"Sunderland"},
			{"Team":"Liverpool", "Number":"23","Name":"Emre Can","Nat":"GER","Pos":"M","Height":"1.86","Weight":"76","DOB":"12-01-94","Birth Place":"Frankfurt am Main","PreviousClub":"Bayer Leverkusen"},
			{"Team":"Liverpool", "Number":"24","Name":"Joe Allen","Nat":"WAL","Pos":"M","Height":"1.68","Weight":"62","DOB":"14-03-90","Birth Place":"Carmarthen","PreviousClub":"Swansea C"},
			{"Team":"Liverpool", "Number":"26","Name":"Tiago Ilori","Nat":"POR","Pos":"D","Height":"1.90","Weight":"80","DOB":"26-02-93","Birth Place":"Hampstead","PreviousClub":"Sporting CP"},
			{"Team":"Liverpool", "Number":"29","Name":"Fabio Borini","Nat":"ITA","Pos":"F","Height":"1.80","Weight":"74","DOB":"29-03-91","Birth Place":"Bentivoglio","PreviousClub":"Roma"},
			{"Team":"Liverpool", "Number":"30","Name":"Suso","Nat":"ESP","Pos":"M","Height":"1.76","Weight":"69","DOB":"19-11-93","Birth Place":"Cádiz","PreviousClub":"Cádiz"},
			{"Team":"Liverpool", "Number":"31","Name":"Raheem Sterling","Nat":"ENG","Pos":"M","Height":"1.70","Weight":"69","DOB":"08-12-94","Birth Place":"Kingston","PreviousClub":"QPR"},
			{"Team":"Liverpool", "Number":"33","Name":"Jordon Ibe","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"70","DOB":"08-12-95","Birth Place":"Southwark","PreviousClub":"Wycombe W"},
			{"Team":"Liverpool", "Number":"34","Name":"Martin Kelly","Nat":"ENG","Pos":"D","Height":"1.91","Weight":"77","DOB":"27-04-90","Birth Place":"Bolton","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"36","Name":"Samed Yeşil","Nat":"GER","Pos":"F","Height":"1.78","Weight":"72","DOB":"25-05-94","Birth Place":"Düsseldorf","PreviousClub":"Bayer Leverkusen"},
			{"Team":"Liverpool", "Number":"37","Name":"Martin Škrteľ","Nat":"SVK","Pos":"D","Height":"1.91","Weight":"81","DOB":"15-12-84","Birth Place":"Handlová","PreviousClub":"Zenit St Petersburg"},
			{"Team":"Liverpool", "Number":"38","Name":"Jon Flanagan","Nat":"ENG","Pos":"D","Height":"1.81","Weight":"79","DOB":"21-01-93","Birth Place":"Liverpool","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"40","Name":"Krisztián Adorján","Nat":"HUN","Pos":"M","Height":"1.80","Weight":"70","DOB":"19-01-93","Birth Place":"Budapest","PreviousClub":"MTK"},
			{"Team":"Liverpool", "Number":"43","Name":"Ryan McLaughlin","Nat":"NIR","Pos":"D","Height":"1.74","Weight":"69","DOB":"03-09-94","Birth Place":"Belfast","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"45","Name":"Adam Phillips","Nat":"ENG","Pos":"M","Height":"","Weight":"","DOB":"15-01-88","Birth Place":"Garstang","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"46","Name":"Jordan Rossiter","Nat":"ENG","Pos":"M","Height":"","Weight":"","DOB":"24-03-97","Birth Place":"Liverpool","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"48","Name":"Jerome Sinclair","Nat":"ENG","Pos":"F","Height":"1.73","Weight":"79","DOB":"20-09-96","Birth Place":"Birmingham","PreviousClub":"WBA"},
			{"Team":"Liverpool", "Number":"49","Name":"Jack Robinson","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"67","DOB":"01-09-93","Birth Place":"Warrington","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"50","Name":"Lazar Marković","Nat":"SRB","Pos":"M","Height":"1.72","Weight":"60","DOB":"02-03-94","Birth Place":"Belgrade","PreviousClub":"Benfica"},
			{"Team":"Liverpool", "Number":"51","Name":"Lloyd Jones","Nat":"ENG","Pos":"D","Height":"1.90","Weight":"75","DOB":"07-10-95","Birth Place":"Plymouth","PreviousClub":"None"},
			{"Team":"Liverpool", "Number":"52","Name":"Danny Ward","Nat":"WAL","Pos":"G","Height":"1.91","Weight":"88","DOB":"22-06-93","Birth Place":"Wrexham","PreviousClub":"Wrexham"},
			{"Team":"Liverpool", "Number":"53","Name":"João Carlos","Nat":"POR","Pos":"M","Height":"1.67","Weight":"66","DOB":"18-01-93","Birth Place":"Braga","PreviousClub":"Sporting CP"},
			{"Team":"Liverpool", "Number":"54","Name":"Kristoffer Peterson","Nat":"SWE","Pos":"M","Height":"1.80","Weight":"70","DOB":"28-11-94","Birth Place":"Gothenburg","PreviousClub":"Sävedalens IF"},
			{"Team":"Man City", "Number":"1","Name":"Joe Hart","Nat":"ENG","Pos":"G","Height":"1.91","Weight":"80","DOB":"19-04-87","Birth Place":"Shrewsbury","PreviousClub":"Shrewsbury T"},
			{"Team":"Man City", "Number":"2","Name":"Micah Richards","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"83","DOB":"24-06-88","Birth Place":"Birmingham","PreviousClub":"None"},
			{"Team":"Man City", "Number":"3","Name":"Bacary Sagna","Nat":"FRA","Pos":"D","Height":"1.76","Weight":"72","DOB":"14-02-83","Birth Place":"Sens","PreviousClub":"Arsenal"},
			{"Team":"Man City", "Number":"4","Name":"Vincent Kompany","Nat":"BEL","Pos":"D","Height":"1.91","Weight":"91","DOB":"10-04-86","Birth Place":"Ukkel","PreviousClub":"Hamburg"},
			{"Team":"Man City", "Number":"5","Name":"Pablo Zabaleta","Nat":"ARG","Pos":"D","Height":"1.74","Weight":"74","DOB":"16-01-85","Birth Place":"Capital Federal","PreviousClub":"Espanyol"},
			{"Team":"Man City", "Number":"6","Name":"Fernando","Nat":"BRA","Pos":"M","Height":"1.83","Weight":"74","DOB":"25-07-87","Birth Place":"Alto Paraíso de Goiás","PreviousClub":"FC Porto"},
			{"Team":"Man City", "Number":"7","Name":"James Milner","Nat":"ENG","Pos":"M","Height":"1.70","Weight":"67","DOB":"04-01-86","Birth Place":"Wortley","PreviousClub":"Aston Villa"},
			{"Team":"Man City", "Number":"8","Name":"Samir Nasri","Nat":"FRA","Pos":"M","Height":"1.77","Weight":"75","DOB":"26-06-87","Birth Place":"Marseille","PreviousClub":"Arsenal"},
			{"Team":"Man City", "Number":"9","Name":"Álvaro Negredo","Nat":"ESP","Pos":"F","Height":"1.86","Weight":"85","DOB":"20-08-85","Birth Place":"Madrid","PreviousClub":"Sevilla"},
			{"Team":"Man City", "Number":"10","Name":"Edin Džeko","Nat":"BIH","Pos":"F","Height":"1.92","Weight":"80","DOB":"17-03-86","Birth Place":"Doboj","PreviousClub":"Wolfsburg"},
			{"Team":"Man City", "Number":"11","Name":"Aleksandar Kolarov","Nat":"SRB","Pos":"D","Height":"1.87","Weight":"83","DOB":"10-11-85","Birth Place":"Belgrade","PreviousClub":"Lazio"},
			{"Team":"Man City", "Number":"12","Name":"Scott Sinclair","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"64","DOB":"25-03-89","Birth Place":"Bath","PreviousClub":"Swansea C"},
			{"Team":"Man City", "Number":"13","Name":"Wilfredo Caballero","Nat":"ARG","Pos":"G","Height":"1.85","Weight":"83","DOB":"28-09-81","Birth Place":"Salta Elena","PreviousClub":"Málaga"},
			{"Team":"Man City", "Number":"14","Name":"Javi García","Nat":"ESP","Pos":"M","Height":"1.86","Weight":"78","DOB":"08-02-87","Birth Place":"Murcia","PreviousClub":"Benfica"},
			{"Team":"Man City", "Number":"15","Name":"Jesús Navas","Nat":"ESP","Pos":"M","Height":"1.70","Weight":"60","DOB":"21-11-85","Birth Place":"Los Palacios","PreviousClub":"Sevilla"},
			{"Team":"Man City", "Number":"16","Name":"Sergio Agüero","Nat":"ARG","Pos":"F","Height":"1.72","Weight":"74","DOB":"02-06-88","Birth Place":"Capital Federal","PreviousClub":"Atlético Madrid"},
			{"Team":"Man City", "Number":"18","Name":"Frank Lampard","Nat":"ENG","Pos":"M","Height":"1.83","Weight":"90","DOB":"20-06-78","Birth Place":"Romford","PreviousClub":"New York C"},
			{"Team":"Man City", "Number":"19","Name":"Karim Rekik","Nat":"NED","Pos":"D","Height":"1.83","Weight":"76","DOB":"02-12-94","Birth Place":"Den Haag","PreviousClub":"Feyenoord"},
			{"Team":"Man City", "Number":"20","Name":"Eliaquim Mangala","Nat":"FRA","Pos":"D","Height":"1.87","Weight":"74","DOB":"13-02-91","Birth Place":"Colombes","PreviousClub":"FC Porto"},
			{"Team":"Man City", "Number":"21","Name":"David Silva","Nat":"ESP","Pos":"M","Height":"1.70","Weight":"67","DOB":"08-01-86","Birth Place":"Arguineguín","PreviousClub":"Valencia"},
			{"Team":"Man City", "Number":"22","Name":"Gaël Clichy","Nat":"FRA","Pos":"D","Height":"1.81","Weight":"72","DOB":"26-07-85","Birth Place":"Toulouse","PreviousClub":"Arsenal"},
			{"Team":"Man City", "Number":"25","Name":"Fernandinho","Nat":"BRA","Pos":"M","Height":"1.76","Weight":"67","DOB":"04-05-85","Birth Place":"Londrina","PreviousClub":"Shakhtar Donetsk"},
			{"Team":"Man City", "Number":"26","Name":"Martin Demichelis","Nat":"ARG","Pos":"D","Height":"1.84","Weight":"78","DOB":"20-12-80","Birth Place":"Justiniano Posse","PreviousClub":"Atlético Madrid"},
			{"Team":"Man City", "Number":"29","Name":"Richard Wright","Nat":"ENG","Pos":"G","Height":"1.87","Weight":"82","DOB":"05-11-77","Birth Place":"Ipswich","PreviousClub":"Preston NE"},
			{"Team":"Man City", "Number":"33","Name":"Matija Nastasić","Nat":"SRB","Pos":"D","Height":"1.87","Weight":"79","DOB":"28-03-93","Birth Place":"Belgrade","PreviousClub":"Fiorentina"},
			{"Team":"Man City", "Number":"35","Name":"Stevan Jovetić","Nat":"MNE","Pos":"F","Height":"1.83","Weight":"79","DOB":"02-11-89","Birth Place":"Podgorica","PreviousClub":"Fiorentina"},
			{"Team":"Man City", "Number":"36","Name":"Bruno Zuculini","Nat":"ARG","Pos":"M","Height":"1.78","Weight":"72","DOB":"02-04-93","Birth Place":"Escobar","PreviousClub":"Racing Club"},
			{"Team":"Man City", "Number":"38","Name":"Dedryck Boyata","Nat":"BEL","Pos":"D","Height":"1.88","Weight":"84","DOB":"08-09-90","Birth Place":"Uccle","PreviousClub":"None"},
			{"Team":"Man City", "Number":"42","Name":"Yaya Touré","Nat":"CIV","Pos":"M","Height":"1.91","Weight":"90","DOB":"13-05-83","Birth Place":"Sokoura Bouaké","PreviousClub":"Barcelona"},
			{"Team":"Man City", "Number":"60","Name":"John Guidetti","Nat":"SWE","Pos":"F","Height":"1.81","Weight":"79","DOB":"15-04-92","Birth Place":"Stockholm","PreviousClub":"IF Brommapojkarna"},
			{"Team": "Man Utd","Number":"1","Name":"David De Gea","Nat":"ESP","Pos":"G","Height":"1.92","Weight":"82","DOB":"07-11-90","Birth Place":"Madrid","PreviousClub":"Atlético Madrid"},
			{"Team": "Man Utd","Number":"2","Name":"Rafael","Nat":"BRA","Pos":"D","Height":"1.72","Weight":"65","DOB":"09-07-90","Birth Place":"Petrópolis","PreviousClub":"Fluminense"},
			{"Team": "Man Utd","Number":"3","Name":"Luke Shaw","Nat":"ENG","Pos":"D","Height":"1.83","Weight":"75","DOB":"12-07-95","Birth Place":"Kingston upon Thames","PreviousClub":"Southampton"},
			{"Team": "Man Utd","Number":"4","Name":"Phil Jones","Nat":"ENG","Pos":"D","Height":"1.80","Weight":"71","DOB":"21-02-92","Birth Place":"Preston","PreviousClub":"Blackburn R"},
			{"Team": "Man Utd","Number":"6","Name":"Jonny Evans","Nat":"NIR","Pos":"D","Height":"1.88","Weight":"77","DOB":"02-01-88","Birth Place":"Belfast","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"8","Name":"Juan Mata","Nat":"ESP","Pos":"F","Height":"1.70","Weight":"63","DOB":"28-04-88","Birth Place":"Burgos","PreviousClub":"Chelsea"},
			{"Team": "Man Utd","Number":"10","Name":"Wayne Rooney","Nat":"ENG","Pos":"F","Height":"1.78","Weight":"78","DOB":"24-10-85","Birth Place":"Croxteth","PreviousClub":"Everton"},
			{"Team": "Man Utd","Number":"11","Name":"Adnan Januzaj","Nat":"BEL","Pos":"M","Height":"1.80","Weight":"75","DOB":"05-02-95","Birth Place":"Brussels","PreviousClub":"Anderlecht"},
			{"Team": "Man Utd","Number":"12","Name":"Chris Smalling","Nat":"ENG","Pos":"D","Height":"1.93","Weight":"90","DOB":"22-11-89","Birth Place":"Greenwich","PreviousClub":"Fulham"},
			{"Team": "Man Utd","Number":"13","Name":"Anders Lindegaard","Nat":"DEN","Pos":"G","Height":"1.93","Weight":"80","DOB":"13-04-84","Birth Place":"Odense","PreviousClub":"Aalesund"},
			{"Team": "Man Utd","Number":"14","Name":"Javier Hernández","Nat":"MEX","Pos":"F","Height":"1.72","Weight":"62","DOB":"01-06-88","Birth Place":"Guadalajara","PreviousClub":"Guadalajara"},
			{"Team": "Man Utd","Number":"16","Name":"Michael Carrick","Nat":"ENG","Pos":"M","Height":"1.86","Weight":"74","DOB":"28-07-81","Birth Place":"Wallsend","PreviousClub":"Tottenham H"},
			{"Team": "Man Utd","Number":"17","Name":"Nani","Nat":"POR","Pos":"M","Height":"1.75","Weight":"66","DOB":"17-11-86","Birth Place":"Praia","PreviousClub":"Sporting CP"},
			{"Team": "Man Utd","Number":"18","Name":"Ashley Young","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"65","DOB":"09-07-85","Birth Place":"Stevenage","PreviousClub":"Aston Villa"},
			{"Team": "Man Utd","Number":"19","Name":"Danny Welbeck","Nat":"ENG","Pos":"F","Height":"1.85","Weight":"73","DOB":"26-11-90","Birth Place":"Manchester","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"20","Name":"Robin van Persie","Nat":"NED","Pos":"F","Height":"1.83","Weight":"71","DOB":"06-08-83","Birth Place":"Rotterdam","PreviousClub":"Arsenal"},
			{"Team": "Man Utd","Number":"21","Name":"Ander Herrera","Nat":"ESP","Pos":"M","Height":"1.81","Weight":"68","DOB":"14-08-89","Birth Place":"Bilbao","PreviousClub":"Athletic Bilbao"},
			{"Team": "Man Utd","Number":"22","Name":"Nick Powell","Nat":"ENG","Pos":"M","Height":"1.83","Weight":"66","DOB":"23-03-94","Birth Place":"Crewe","PreviousClub":"Crewe Alex"},
			{"Team": "Man Utd","Number":"23","Name":"Tom Cleverley","Nat":"ENG","Pos":"M","Height":"1.75","Weight":"67","DOB":"12-08-89","Birth Place":"Basingstoke","PreviousClub":"Bradford C"},
			{"Team": "Man Utd","Number":"24","Name":"Darren Fletcher","Nat":"SCO","Pos":"M","Height":"1.83","Weight":"83","DOB":"01-02-84","Birth Place":"Edinburgh","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"25","Name":"Luis Antonio Valencia","Nat":"ECU","Pos":"M","Height":"1.81","Weight":"78","DOB":"04-08-85","Birth Place":"Lago Agrio","PreviousClub":"Wigan Ath"},
			{"Team": "Man Utd","Number":"26","Name":"Shinji Kagawa","Nat":"JPN","Pos":"M","Height":"1.72","Weight":"63","DOB":"17-03-89","Birth Place":"Hyogo","PreviousClub":"Borussia Dortmund"},
			{"Team": "Man Utd","Number":"28","Name":"Anderson","Nat":"BRA","Pos":"M","Height":"1.76","Weight":"69","DOB":"13-04-88","Birth Place":"Porto Alegre","PreviousClub":"FC Porto"},
			{"Team": "Man Utd","Number":"29","Name":"Wilfried Zaha","Nat":"ENG","Pos":"F","Height":"1.80","Weight":"66","DOB":"10-11-92","Birth Place":"Abidjan","PreviousClub":"Crystal Palace"},
			{"Team": "Man Utd","Number":"30","Name":"Guillermo Varela","Nat":"URU","Pos":"D","Height":"1.71","Weight":"69","DOB":"24-03-93","Birth Place":"Montevideo","PreviousClub":"Peñarol"},
			{"Team": "Man Utd","Number":"31","Name":"Marouane Fellaini","Nat":"BEL","Pos":"M","Height":"1.94","Weight":"85","DOB":"22-11-87","Birth Place":"Etterbeek","PreviousClub":"Everton"},
			{"Team": "Man Utd","Number":"34","Name":"Tom Lawrence","Nat":"WAL","Pos":"F","Height":"","Weight":"","DOB":"13-01-94","Birth Place":"Wrexham","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"35","Name":"Jesse Lingard","Nat":"ENG","Pos":"M","Height":"1.68","Weight":"58","DOB":"15-12-92","Birth Place":"Warrington","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"36","Name":"Marnick Vermijl","Nat":"BEL","Pos":"D","Height":"1.80","Weight":"70","DOB":"13-01-92","Birth Place":"Peer","PreviousClub":"Standard Liège"},
			{"Team": "Man Utd","Number":"38","Name":"Michael Keane","Nat":"ENG","Pos":"D","Height":"1.72","Weight":"68","DOB":"11-01-93","Birth Place":"Stockport","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"39","Name":"Tom Thorpe","Nat":"ENG","Pos":"D","Height":"1.88","Weight":"89","DOB":"13-01-93","Birth Place":"Manchester","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"40","Name":"Ben Amos","Nat":"ENG","Pos":"G","Height":"1.85","Weight":"83","DOB":"10-04-90","Birth Place":"Macclesfield","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"41","Name":"Reece James","Nat":"ENG","Pos":"D","Height":"","Weight":"","DOB":"07-11-93","Birth Place":"Bacup","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"42","Name":"Tyler Blackett","Nat":"ENG","Pos":"D","Height":"1.86","Weight":"76","DOB":"02-04-94","Birth Place":"Manchester","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"45","Name":"Davide Petrucci","Nat":"ITA","Pos":"M","Height":"1.88","Weight":"88","DOB":"17-10-91","Birth Place":"Rome","PreviousClub":"Roma"},
			{"Team": "Man Utd","Number":"46","Name":"Joe Rothwell","Nat":"ENG","Pos":"M","Height":"","Weight":"","DOB":"11-01-95","Birth Place":"Manchester","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"48","Name":"Will Keane","Nat":"ENG","Pos":"F","Height":"1.78","Weight":"78","DOB":"11-01-93","Birth Place":"Stockport","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"49","Name":"James Wilson","Nat":"ENG","Pos":"F","Height":"1.84","Weight":"78","DOB":"01-12-95","Birth Place":"Biddulph","PreviousClub":"None"},
			{"Team": "Man Utd","Number":"50","Name":"Sam Johnstone","Nat":"ENG","Pos":"G","Height":"1.93","Weight":"85","DOB":"25-03-93","Birth Place":"Preston","PreviousClub":"None"}
			]
	}
]